ifeq ($(CXX), cc)
CXX=g++
endif
CFLAGS=`pkg-config directfb direct --cflags`
LDFLAGS=`pkg-config directfb direct --libs` 

SOURCES = Main.cpp \
	Utils.cpp \
	File.cpp \
	Application.cpp \
	Renderer.cpp \
	Box.cpp \
	Widget.cpp \
	Screen.cpp \
	Menu.cpp \
	MenuItem.cpp \
	MainMenu.cpp \
	MoviesMenu.cpp 

OBJECTS = $(SOURCES:.cpp=.o)
APP = nmti

all: $(SOURCES) $(APP)

$(APP): $(OBJECTS)
	$(CXX) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	cat config.in > config.h
	$(CXX) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJECTS) $(APP) *~